APP = backend

CC = gcc
LIBEVENT = /usr/local
LIBEVENT_LIB = "${LIBEVENT}/lib"
LIBEVENT_INCLUDE = "${LIBEVENT}/include"
CFLAGS = -fno-strict-aliasing -O3 -w -pipe -DNDEBUG -g -fwrapv -Wall -Wstrict-prototypes -lrt
CFLAGS += -I$(LIBEVENT_INCLUDE) -Isrc -L$(LIBEVENT_LIB) -L/usr/local/lib -L/usr/lib
SOURCES = $(LIBEVENT_LIB)/libevent.a $(LIBEVENT_LIB)/libevent_core.a $(LIBEVENT_LIB)/libevent_extra.a $(LIBEVENT_LIB)/libevent_pthreads.a

all :
	 $(CC) $(CFLAGS) -o $(APP) src/main.c $(SOURCES)
