#!/bin/bash

ulimit -n 16384

RUNS="1 2 4 8 16 32 64 128 256 512 1024"
RUNS="256 512 1024 2048"

#COUNT="65535"
COUNT="8192"
DATA_DIR="/tmp/"
SUFFIX="plotdata"

TARGET=$1
LABEL=$( echo $TARGET | sed -e 's/\./-/g' )

if [ "x$2" == "x" ]
then
  TARGET_PATH='/'
else
  TARGET_PATH=$2
fi

HTML="$DATA_DIR/$LABEL.html"

TARGET="http://${TARGET}${TARGET_PATH}"

function make_plot () {
        echo "set terminal png"
        echo "set output \"$1.png\""
        echo "set xlabel \"Request\""
        echo "set ylabel \"ms\""
        echo "plot \"$1\" using 10 with lines title \"Response time\""
}

function graph2html () {
        for i in $@
        do
                src=$(basename $i)
                header=$(echo $src | awk -F. '{print $1}')
                echo "<p><h1>$header</h1> <img src='$src'> </p>" >> $HTML
        done
}


if [ ! -d "${DATA_DIR}" ]
then
        mkdir -p "${DATA_DIR}"
fi

if [ "x$1" != "x" ]
then 
        KEEP_ALIVE=""
else
        KEEP_ALIVE="ON"
fi


echo "================================================================================"
echo "<html>" > $HTML

for i in $RUNS
do
        ARGS="-n $COUNT -c $i -g ${DATA_DIR}/${LABEL}-${i}.${SUFFIX}"

        if [ "x$KEEP_ALIVE" == "xON" ]
        then
                ARGS="-k $ARGS"
        fi

        ab $ARGS $TARGET
        graph2html "$DATA_DIR/$LABEL-${i}.${SUFFIX}.png"

        sleep 30
done

echo "</html>" >> $HTML
echo "================================================================================"

for i in $RUNS
do
        make_plot "${DATA_DIR}/${LABEL}-${i}.${SUFFIX}" | gnuplot
done
